baseURL = "https://tmduc2606.github.io/"
languageCode = "en-us"
title = "Cresht Tran"
copyright = "Cresht."
theme = "diary"
DefaultContentLanguage = "en"

[params]
  subtitle = "When all that lies ahead is struggle, choose the path of greatest resistance"
  description = "Undergraduate of Computer Science at International University, VNU-HCM. Interests in NLP, Data Science/AI, and Data Engineering."
  enableGitalk = false
  enableGiscus = false
  enableReadingTime = true
  enableOpenGraph = true
  enableTwitterCards = true
  walineServer = "https://waline-blog-rho-three.vercel.app/"

  [params.waline]
    emoji = ["//unpkg.com/@waline/emojis@latest/bilibili"]
    requiredMeta = ["nick", "mail"]

[params.social]
  email = "mailto:tmduc2606@gmail.com"
  facebook = "https://www.facebook.com/tmduc2606/"
  linkedin = "https://www.linkedin.com/in/tmduc2606/"
  github = "https://github.com/tmduc2606"
  kaggle = "https://www.kaggle.com/cresht2606"

[[menu.main]]
url = "/"
name = "Home"
weight = 1

[[menu.main]]
url = "/academic/"
name = "Academic"
weight = 2

[[menu.main]]
url = "/projects/"
name = "Projects"
weight = 3

[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 4

[[menu.main]]
url = "/contact/"
name = "Contact"
weight = 5

[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    style = "onedark"
    lineNos = false
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

